baseURL = 'https://isabellatessier.co.uk/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'art-hugo-theme'

[taxonomies]
    tag = 'tags'

[params]

    title = 'Isabella Tessier'
     
    instagram = 'https://www.instagram.com/isabella.tessier/'
    linkedin = 'https://www.linkedin.com/in/issy-tessier-940a7a188/'


    [[params.navlinks]]
    name = "Drawings"
    url = "drawings"

    [[params.navlinks]]
    name = "Exhibitions"
    url = "exhibitions"

    [[params.navlinks]]
    name = "Prints"
    url = "prints"

    [[params.navlinks]]
    name = "About"
    url = "about"


