baseURL = 'https://isabellatessier.co.uk/'
languageCode = 'en-uk'
title = 'Isabella Tessier'
theme = 'art-hugo-theme'
paginate = 8

[taxonomies]
    tag = 'tags'

[params]

    title = 'Isabella Tessier'

    featuredTitle = 'Shortlisted for The Clifford Chance Purchase Prize 2024'  
    instagram = 'https://www.instagram.com/isabella.tessier/'
    linkedin = 'https://www.linkedin.com/in/issy-tessier-940a7a188/'

    footerMessage = '© 2023 - Isabella Tessier: issy.tessier@gmail.com'

    [[params.navlinks]]
    name = "Exhibitions"
    url = "exhibitions"
    
     [[params.navlinks]]
    name = "Prints"
    url = "prints"

    [[params.navlinks]]
    name = "Drawings"
    url = "drawings"

    [[params.navlinks]]
    name = "About"
    url = "about"


